/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_ode_gnsf_phi_jac_y_uhat_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s3[44] = {7, 7, 0, 4, 8, 12, 16, 22, 28, 34, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 5, 6, 0, 1, 2, 3, 4, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[19] = {7, 4, 0, 3, 6, 9, 12, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6};

/* drone_ode_gnsf_phi_jac_y_uhat:(i0[7],i1[4],i2[21])->(o0[7x7,34nz],o1[7x4,12nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=5.0000000000000000e-01;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[0]? arg[0][1] : 0;
  a3=arg[0]? arg[0][0] : 0;
  a4=casadi_sq(a3);
  a5=casadi_sq(a2);
  a4=(a4+a5);
  a5=arg[0]? arg[0][2] : 0;
  a6=casadi_sq(a5);
  a4=(a4+a6);
  a6=arg[0]? arg[0][3] : 0;
  a7=casadi_sq(a6);
  a4=(a4+a7);
  a7=(a2/a4);
  a8=(a7/a4);
  a9=(a3+a3);
  a10=(a8*a9);
  a11=(a1*a10);
  a12=arg[0]? arg[0][5] : 0;
  a13=(a5/a4);
  a14=(a13/a4);
  a15=(a14*a9);
  a16=(a12*a15);
  a11=(a11+a16);
  a16=arg[0]? arg[0][6] : 0;
  a17=(a6/a4);
  a18=(a17/a4);
  a19=(a18*a9);
  a20=(a16*a19);
  a11=(a11+a20);
  a11=(a0*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][0]=a11;
  a11=(1./a4);
  a3=(a3/a4);
  a20=(a3/a4);
  a9=(a20*a9);
  a11=(a11-a9);
  a9=(a1*a11);
  a21=(a12*a19);
  a22=(a16*a15);
  a21=(a21-a22);
  a9=(a9+a21);
  a9=(a0*a9);
  a9=(-a9);
  if (res[0]!=0) res[0][1]=a9;
  a9=(a12*a11);
  a21=(a16*a10);
  a19=(a1*a19);
  a21=(a21-a19);
  a9=(a9+a21);
  a9=(a0*a9);
  a9=(-a9);
  if (res[0]!=0) res[0][2]=a9;
  a11=(a16*a11);
  a15=(a1*a15);
  a10=(a12*a10);
  a15=(a15-a10);
  a11=(a11+a15);
  a11=(a0*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][3]=a11;
  a11=(1./a4);
  a2=(a2+a2);
  a15=(a8*a2);
  a11=(a11-a15);
  a15=(a1*a11);
  a10=(a14*a2);
  a9=(a12*a10);
  a15=(a15-a9);
  a9=(a18*a2);
  a21=(a16*a9);
  a15=(a15-a21);
  a15=(a0*a15);
  if (res[0]!=0) res[0][4]=a15;
  a15=(a12*a9);
  a21=(a16*a10);
  a15=(a15-a21);
  a2=(a20*a2);
  a21=(a1*a2);
  a15=(a15-a21);
  a15=(a0*a15);
  a15=(-a15);
  if (res[0]!=0) res[0][5]=a15;
  a15=(a12*a2);
  a9=(a1*a9);
  a21=(a16*a11);
  a9=(a9+a21);
  a15=(a15+a9);
  a15=(a0*a15);
  if (res[0]!=0) res[0][6]=a15;
  a11=(a12*a11);
  a10=(a1*a10);
  a11=(a11+a10);
  a2=(a16*a2);
  a11=(a11-a2);
  a11=(a0*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][7]=a11;
  a11=(1./a4);
  a5=(a5+a5);
  a2=(a14*a5);
  a11=(a11-a2);
  a2=(a12*a11);
  a10=(a8*a5);
  a15=(a1*a10);
  a2=(a2-a15);
  a15=(a18*a5);
  a9=(a16*a15);
  a2=(a2-a9);
  a2=(a0*a2);
  if (res[0]!=0) res[0][8]=a2;
  a2=(a16*a11);
  a9=(a12*a15);
  a2=(a2+a9);
  a5=(a20*a5);
  a9=(a1*a5);
  a2=(a2-a9);
  a2=(a0*a2);
  a2=(-a2);
  if (res[0]!=0) res[0][9]=a2;
  a2=(a16*a10);
  a15=(a1*a15);
  a2=(a2-a15);
  a15=(a12*a5);
  a2=(a2-a15);
  a2=(a0*a2);
  a2=(-a2);
  if (res[0]!=0) res[0][10]=a2;
  a5=(a16*a5);
  a10=(a12*a10);
  a11=(a1*a11);
  a10=(a10+a11);
  a5=(a5+a10);
  a5=(a0*a5);
  if (res[0]!=0) res[0][11]=a5;
  a4=(1./a4);
  a6=(a6+a6);
  a18=(a18*a6);
  a4=(a4-a18);
  a18=(a16*a4);
  a8=(a8*a6);
  a5=(a1*a8);
  a14=(a14*a6);
  a10=(a12*a14);
  a5=(a5+a10);
  a18=(a18-a5);
  a18=(a0*a18);
  if (res[0]!=0) res[0][12]=a18;
  a20=(a20*a6);
  a6=(a1*a20);
  a18=(a16*a14);
  a5=(a12*a4);
  a18=(a18+a5);
  a6=(a6+a18);
  a6=(a0*a6);
  if (res[0]!=0) res[0][13]=a6;
  a4=(a1*a4);
  a6=(a16*a8);
  a4=(a4+a6);
  a6=(a12*a20);
  a4=(a4-a6);
  a4=(a0*a4);
  a4=(-a4);
  if (res[0]!=0) res[0][14]=a4;
  a14=(a1*a14);
  a8=(a12*a8);
  a14=(a14-a8);
  a20=(a16*a20);
  a14=(a14-a20);
  a14=(a0*a14);
  a14=(-a14);
  if (res[0]!=0) res[0][15]=a14;
  a14=(a0*a7);
  if (res[0]!=0) res[0][16]=a14;
  a14=(a0*a3);
  a14=(-a14);
  if (res[0]!=0) res[0][17]=a14;
  a14=(a0*a17);
  a14=(-a14);
  if (res[0]!=0) res[0][18]=a14;
  a14=(a0*a13);
  if (res[0]!=0) res[0][19]=a14;
  a14=arg[2]? arg[2][2] : 0;
  a20=(a16*a14);
  a8=arg[2]? arg[2][4] : 0;
  a4=(a8*a16);
  a20=(a20-a4);
  a6=arg[2]? arg[2][3] : 0;
  a20=(a20/a6);
  if (res[0]!=0) res[0][20]=a20;
  a20=(a6*a12);
  a18=(a12*a14);
  a18=(a20-a18);
  a18=(a18/a8);
  if (res[0]!=0) res[0][21]=a18;
  a18=(a0*a13);
  if (res[0]!=0) res[0][22]=a18;
  a18=(a0*a17);
  if (res[0]!=0) res[0][23]=a18;
  a18=(a0*a3);
  a18=(-a18);
  if (res[0]!=0) res[0][24]=a18;
  a18=(a0*a7);
  a18=(-a18);
  if (res[0]!=0) res[0][25]=a18;
  a16=(a16*a6);
  a4=(a4-a16);
  a4=(a4/a14);
  if (res[0]!=0) res[0][26]=a4;
  a4=(a1*a6);
  a16=(a14*a1);
  a4=(a4-a16);
  a4=(a4/a8);
  if (res[0]!=0) res[0][27]=a4;
  a17=(a0*a17);
  if (res[0]!=0) res[0][28]=a17;
  a13=(a0*a13);
  a13=(-a13);
  if (res[0]!=0) res[0][29]=a13;
  a7=(a0*a7);
  if (res[0]!=0) res[0][30]=a7;
  a0=(a0*a3);
  a0=(-a0);
  if (res[0]!=0) res[0][31]=a0;
  a12=(a12*a8);
  a12=(a12-a20);
  a12=(a12/a14);
  if (res[0]!=0) res[0][32]=a12;
  a1=(a1*a8);
  a16=(a16-a1);
  a16=(a16/a6);
  if (res[0]!=0) res[0][33]=a16;
  a16=arg[2]? arg[2][5] : 0;
  a16=(a16/a14);
  if (res[1]!=0) res[1][0]=a16;
  a16=arg[2]? arg[2][9] : 0;
  a16=(a16/a6);
  a16=(-a16);
  if (res[1]!=0) res[1][1]=a16;
  a16=arg[2]? arg[2][13] : 0;
  a1=(a16/a8);
  if (res[1]!=0) res[1][2]=a1;
  a1=arg[2]? arg[2][6] : 0;
  a1=(a1/a14);
  if (res[1]!=0) res[1][3]=a1;
  a1=arg[2]? arg[2][10] : 0;
  a1=(a1/a6);
  if (res[1]!=0) res[1][4]=a1;
  a1=(a16/a8);
  a1=(-a1);
  if (res[1]!=0) res[1][5]=a1;
  a1=arg[2]? arg[2][7] : 0;
  a1=(a1/a14);
  a1=(-a1);
  if (res[1]!=0) res[1][6]=a1;
  a1=arg[2]? arg[2][11] : 0;
  a1=(a1/a6);
  if (res[1]!=0) res[1][7]=a1;
  a1=(a16/a8);
  if (res[1]!=0) res[1][8]=a1;
  a1=arg[2]? arg[2][8] : 0;
  a1=(a1/a14);
  a1=(-a1);
  if (res[1]!=0) res[1][9]=a1;
  a1=arg[2]? arg[2][12] : 0;
  a1=(a1/a6);
  a1=(-a1);
  if (res[1]!=0) res[1][10]=a1;
  a16=(a16/a8);
  a16=(-a16);
  if (res[1]!=0) res[1][11]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_jac_y_uhat(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_jac_y_uhat_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_jac_y_uhat_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_phi_jac_y_uhat_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_jac_y_uhat_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_phi_jac_y_uhat_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_phi_jac_y_uhat_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_phi_jac_y_uhat_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_gnsf_phi_jac_y_uhat_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_gnsf_phi_jac_y_uhat_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real drone_ode_gnsf_phi_jac_y_uhat_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_gnsf_phi_jac_y_uhat_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_gnsf_phi_jac_y_uhat_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_gnsf_phi_jac_y_uhat_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_gnsf_phi_jac_y_uhat_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_jac_y_uhat_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_jac_y_uhat_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
