/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_ode_gnsf_get_matrices_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[35] = {7, 4, 0, 7, 14, 21, 28, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s3[3] = {7, 0, 0};
static const casadi_int casadi_s4[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s7[7] = {0, 4, 0, 0, 0, 0, 0};
static const casadi_int casadi_s8[4] = {0, 1, 0, 0};

/* drone_ode_gnsf_get_matrices_fun:(i0)->(o0[7x7],o1[7x4],o2[7x7],o3[7x7],o4[7x7],o5[7x7],o6[7x0],o7[4x4],o8[],o9[7],o10[],o11[0x4],o12,o13,o14[7],o15[0],o16[0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a0;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a0;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a0;
  if (res[0]!=0) res[0][42]=a0;
  if (res[0]!=0) res[0][43]=a0;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a0;
  if (res[0]!=0) res[0][46]=a0;
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a0;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a0;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a0;
  if (res[1]!=0) res[1][9]=a0;
  if (res[1]!=0) res[1][10]=a0;
  if (res[1]!=0) res[1][11]=a0;
  if (res[1]!=0) res[1][12]=a0;
  if (res[1]!=0) res[1][13]=a0;
  if (res[1]!=0) res[1][14]=a0;
  if (res[1]!=0) res[1][15]=a0;
  if (res[1]!=0) res[1][16]=a0;
  if (res[1]!=0) res[1][17]=a0;
  if (res[1]!=0) res[1][18]=a0;
  if (res[1]!=0) res[1][19]=a0;
  if (res[1]!=0) res[1][20]=a0;
  if (res[1]!=0) res[1][21]=a0;
  if (res[1]!=0) res[1][22]=a0;
  if (res[1]!=0) res[1][23]=a0;
  if (res[1]!=0) res[1][24]=a0;
  if (res[1]!=0) res[1][25]=a0;
  if (res[1]!=0) res[1][26]=a0;
  if (res[1]!=0) res[1][27]=a0;
  a1=1.;
  if (res[2]!=0) res[2][0]=a1;
  if (res[2]!=0) res[2][1]=a0;
  if (res[2]!=0) res[2][2]=a0;
  if (res[2]!=0) res[2][3]=a0;
  if (res[2]!=0) res[2][4]=a0;
  if (res[2]!=0) res[2][5]=a0;
  if (res[2]!=0) res[2][6]=a0;
  if (res[2]!=0) res[2][7]=a0;
  if (res[2]!=0) res[2][8]=a1;
  if (res[2]!=0) res[2][9]=a0;
  if (res[2]!=0) res[2][10]=a0;
  if (res[2]!=0) res[2][11]=a0;
  if (res[2]!=0) res[2][12]=a0;
  if (res[2]!=0) res[2][13]=a0;
  if (res[2]!=0) res[2][14]=a0;
  if (res[2]!=0) res[2][15]=a0;
  if (res[2]!=0) res[2][16]=a1;
  if (res[2]!=0) res[2][17]=a0;
  if (res[2]!=0) res[2][18]=a0;
  if (res[2]!=0) res[2][19]=a0;
  if (res[2]!=0) res[2][20]=a0;
  if (res[2]!=0) res[2][21]=a0;
  if (res[2]!=0) res[2][22]=a0;
  if (res[2]!=0) res[2][23]=a0;
  if (res[2]!=0) res[2][24]=a1;
  if (res[2]!=0) res[2][25]=a0;
  if (res[2]!=0) res[2][26]=a0;
  if (res[2]!=0) res[2][27]=a0;
  if (res[2]!=0) res[2][28]=a0;
  if (res[2]!=0) res[2][29]=a0;
  if (res[2]!=0) res[2][30]=a0;
  if (res[2]!=0) res[2][31]=a0;
  if (res[2]!=0) res[2][32]=a1;
  if (res[2]!=0) res[2][33]=a0;
  if (res[2]!=0) res[2][34]=a0;
  if (res[2]!=0) res[2][35]=a0;
  if (res[2]!=0) res[2][36]=a0;
  if (res[2]!=0) res[2][37]=a0;
  if (res[2]!=0) res[2][38]=a0;
  if (res[2]!=0) res[2][39]=a0;
  if (res[2]!=0) res[2][40]=a1;
  if (res[2]!=0) res[2][41]=a0;
  if (res[2]!=0) res[2][42]=a0;
  if (res[2]!=0) res[2][43]=a0;
  if (res[2]!=0) res[2][44]=a0;
  if (res[2]!=0) res[2][45]=a0;
  if (res[2]!=0) res[2][46]=a0;
  if (res[2]!=0) res[2][47]=a0;
  if (res[2]!=0) res[2][48]=a1;
  a2=-1.;
  if (res[3]!=0) res[3][0]=a2;
  if (res[3]!=0) res[3][1]=a0;
  if (res[3]!=0) res[3][2]=a0;
  if (res[3]!=0) res[3][3]=a0;
  if (res[3]!=0) res[3][4]=a0;
  if (res[3]!=0) res[3][5]=a0;
  if (res[3]!=0) res[3][6]=a0;
  if (res[3]!=0) res[3][7]=a0;
  if (res[3]!=0) res[3][8]=a2;
  if (res[3]!=0) res[3][9]=a0;
  if (res[3]!=0) res[3][10]=a0;
  if (res[3]!=0) res[3][11]=a0;
  if (res[3]!=0) res[3][12]=a0;
  if (res[3]!=0) res[3][13]=a0;
  if (res[3]!=0) res[3][14]=a0;
  if (res[3]!=0) res[3][15]=a0;
  if (res[3]!=0) res[3][16]=a2;
  if (res[3]!=0) res[3][17]=a0;
  if (res[3]!=0) res[3][18]=a0;
  if (res[3]!=0) res[3][19]=a0;
  if (res[3]!=0) res[3][20]=a0;
  if (res[3]!=0) res[3][21]=a0;
  if (res[3]!=0) res[3][22]=a0;
  if (res[3]!=0) res[3][23]=a0;
  if (res[3]!=0) res[3][24]=a2;
  if (res[3]!=0) res[3][25]=a0;
  if (res[3]!=0) res[3][26]=a0;
  if (res[3]!=0) res[3][27]=a0;
  if (res[3]!=0) res[3][28]=a0;
  if (res[3]!=0) res[3][29]=a0;
  if (res[3]!=0) res[3][30]=a0;
  if (res[3]!=0) res[3][31]=a0;
  if (res[3]!=0) res[3][32]=a2;
  if (res[3]!=0) res[3][33]=a0;
  if (res[3]!=0) res[3][34]=a0;
  if (res[3]!=0) res[3][35]=a0;
  if (res[3]!=0) res[3][36]=a0;
  if (res[3]!=0) res[3][37]=a0;
  if (res[3]!=0) res[3][38]=a0;
  if (res[3]!=0) res[3][39]=a0;
  if (res[3]!=0) res[3][40]=a2;
  if (res[3]!=0) res[3][41]=a0;
  if (res[3]!=0) res[3][42]=a0;
  if (res[3]!=0) res[3][43]=a0;
  if (res[3]!=0) res[3][44]=a0;
  if (res[3]!=0) res[3][45]=a0;
  if (res[3]!=0) res[3][46]=a0;
  if (res[3]!=0) res[3][47]=a0;
  if (res[3]!=0) res[3][48]=a2;
  if (res[4]!=0) res[4][0]=a1;
  if (res[4]!=0) res[4][1]=a0;
  if (res[4]!=0) res[4][2]=a0;
  if (res[4]!=0) res[4][3]=a0;
  if (res[4]!=0) res[4][4]=a0;
  if (res[4]!=0) res[4][5]=a0;
  if (res[4]!=0) res[4][6]=a0;
  if (res[4]!=0) res[4][7]=a0;
  if (res[4]!=0) res[4][8]=a1;
  if (res[4]!=0) res[4][9]=a0;
  if (res[4]!=0) res[4][10]=a0;
  if (res[4]!=0) res[4][11]=a0;
  if (res[4]!=0) res[4][12]=a0;
  if (res[4]!=0) res[4][13]=a0;
  if (res[4]!=0) res[4][14]=a0;
  if (res[4]!=0) res[4][15]=a0;
  if (res[4]!=0) res[4][16]=a1;
  if (res[4]!=0) res[4][17]=a0;
  if (res[4]!=0) res[4][18]=a0;
  if (res[4]!=0) res[4][19]=a0;
  if (res[4]!=0) res[4][20]=a0;
  if (res[4]!=0) res[4][21]=a0;
  if (res[4]!=0) res[4][22]=a0;
  if (res[4]!=0) res[4][23]=a0;
  if (res[4]!=0) res[4][24]=a1;
  if (res[4]!=0) res[4][25]=a0;
  if (res[4]!=0) res[4][26]=a0;
  if (res[4]!=0) res[4][27]=a0;
  if (res[4]!=0) res[4][28]=a0;
  if (res[4]!=0) res[4][29]=a0;
  if (res[4]!=0) res[4][30]=a0;
  if (res[4]!=0) res[4][31]=a0;
  if (res[4]!=0) res[4][32]=a1;
  if (res[4]!=0) res[4][33]=a0;
  if (res[4]!=0) res[4][34]=a0;
  if (res[4]!=0) res[4][35]=a0;
  if (res[4]!=0) res[4][36]=a0;
  if (res[4]!=0) res[4][37]=a0;
  if (res[4]!=0) res[4][38]=a0;
  if (res[4]!=0) res[4][39]=a0;
  if (res[4]!=0) res[4][40]=a1;
  if (res[4]!=0) res[4][41]=a0;
  if (res[4]!=0) res[4][42]=a0;
  if (res[4]!=0) res[4][43]=a0;
  if (res[4]!=0) res[4][44]=a0;
  if (res[4]!=0) res[4][45]=a0;
  if (res[4]!=0) res[4][46]=a0;
  if (res[4]!=0) res[4][47]=a0;
  if (res[4]!=0) res[4][48]=a1;
  if (res[5]!=0) res[5][0]=a0;
  if (res[5]!=0) res[5][1]=a0;
  if (res[5]!=0) res[5][2]=a0;
  if (res[5]!=0) res[5][3]=a0;
  if (res[5]!=0) res[5][4]=a0;
  if (res[5]!=0) res[5][5]=a0;
  if (res[5]!=0) res[5][6]=a0;
  if (res[5]!=0) res[5][7]=a0;
  if (res[5]!=0) res[5][8]=a0;
  if (res[5]!=0) res[5][9]=a0;
  if (res[5]!=0) res[5][10]=a0;
  if (res[5]!=0) res[5][11]=a0;
  if (res[5]!=0) res[5][12]=a0;
  if (res[5]!=0) res[5][13]=a0;
  if (res[5]!=0) res[5][14]=a0;
  if (res[5]!=0) res[5][15]=a0;
  if (res[5]!=0) res[5][16]=a0;
  if (res[5]!=0) res[5][17]=a0;
  if (res[5]!=0) res[5][18]=a0;
  if (res[5]!=0) res[5][19]=a0;
  if (res[5]!=0) res[5][20]=a0;
  if (res[5]!=0) res[5][21]=a0;
  if (res[5]!=0) res[5][22]=a0;
  if (res[5]!=0) res[5][23]=a0;
  if (res[5]!=0) res[5][24]=a0;
  if (res[5]!=0) res[5][25]=a0;
  if (res[5]!=0) res[5][26]=a0;
  if (res[5]!=0) res[5][27]=a0;
  if (res[5]!=0) res[5][28]=a0;
  if (res[5]!=0) res[5][29]=a0;
  if (res[5]!=0) res[5][30]=a0;
  if (res[5]!=0) res[5][31]=a0;
  if (res[5]!=0) res[5][32]=a0;
  if (res[5]!=0) res[5][33]=a0;
  if (res[5]!=0) res[5][34]=a0;
  if (res[5]!=0) res[5][35]=a0;
  if (res[5]!=0) res[5][36]=a0;
  if (res[5]!=0) res[5][37]=a0;
  if (res[5]!=0) res[5][38]=a0;
  if (res[5]!=0) res[5][39]=a0;
  if (res[5]!=0) res[5][40]=a0;
  if (res[5]!=0) res[5][41]=a0;
  if (res[5]!=0) res[5][42]=a0;
  if (res[5]!=0) res[5][43]=a0;
  if (res[5]!=0) res[5][44]=a0;
  if (res[5]!=0) res[5][45]=a0;
  if (res[5]!=0) res[5][46]=a0;
  if (res[5]!=0) res[5][47]=a0;
  if (res[5]!=0) res[5][48]=a0;
  if (res[7]!=0) res[7][0]=a1;
  if (res[7]!=0) res[7][1]=a0;
  if (res[7]!=0) res[7][2]=a0;
  if (res[7]!=0) res[7][3]=a0;
  if (res[7]!=0) res[7][4]=a0;
  if (res[7]!=0) res[7][5]=a1;
  if (res[7]!=0) res[7][6]=a0;
  if (res[7]!=0) res[7][7]=a0;
  if (res[7]!=0) res[7][8]=a0;
  if (res[7]!=0) res[7][9]=a0;
  if (res[7]!=0) res[7][10]=a1;
  if (res[7]!=0) res[7][11]=a0;
  if (res[7]!=0) res[7][12]=a0;
  if (res[7]!=0) res[7][13]=a0;
  if (res[7]!=0) res[7][14]=a0;
  if (res[7]!=0) res[7][15]=a1;
  if (res[9]!=0) res[9][0]=a0;
  if (res[9]!=0) res[9][1]=a0;
  if (res[9]!=0) res[9][2]=a0;
  if (res[9]!=0) res[9][3]=a0;
  if (res[9]!=0) res[9][4]=a0;
  if (res[9]!=0) res[9][5]=a0;
  if (res[9]!=0) res[9][6]=a0;
  if (res[12]!=0) res[12][0]=a0;
  if (res[13]!=0) res[13][0]=a0;
  if (res[14]!=0) res[14][0]=a0;
  if (res[14]!=0) res[14][1]=a1;
  a1=2.;
  if (res[14]!=0) res[14][2]=a1;
  a1=3.;
  if (res[14]!=0) res[14][3]=a1;
  a1=4.;
  if (res[14]!=0) res[14][4]=a1;
  a1=5.;
  if (res[14]!=0) res[14][5]=a1;
  a1=6.;
  if (res[14]!=0) res[14][6]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_get_matrices_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_get_matrices_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_get_matrices_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_get_matrices_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_get_matrices_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_get_matrices_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_get_matrices_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_get_matrices_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_gnsf_get_matrices_fun_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_gnsf_get_matrices_fun_n_out(void) { return 17;}

CASADI_SYMBOL_EXPORT casadi_real drone_ode_gnsf_get_matrices_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_gnsf_get_matrices_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_gnsf_get_matrices_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    case 5: return "o5";
    case 6: return "o6";
    case 7: return "o7";
    case 8: return "o8";
    case 9: return "o9";
    case 10: return "o10";
    case 11: return "o11";
    case 12: return "o12";
    case 13: return "o13";
    case 14: return "o14";
    case 15: return "o15";
    case 16: return "o16";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_gnsf_get_matrices_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_gnsf_get_matrices_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s1;
    case 6: return casadi_s3;
    case 7: return casadi_s4;
    case 8: return casadi_s5;
    case 9: return casadi_s6;
    case 10: return casadi_s5;
    case 11: return casadi_s7;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s6;
    case 15: return casadi_s8;
    case 16: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_get_matrices_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_get_matrices_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
