/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_ode_gnsf_phi_fun_jac_y_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[31] = {27, 1, 0, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26};
static const casadi_int casadi_s3[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s4[56] = {7, 11, 0, 3, 6, 9, 12, 18, 24, 30, 33, 36, 39, 42, 1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2, 0, 1, 2, 3, 5, 6, 0, 1, 2, 3, 4, 6, 0, 1, 2, 3, 4, 5, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6};

/* drone_ode_gnsf_phi_fun_jac_y:(i0[11],i1[0],i2[27])->(o0[7],o1[7x11,42nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][1] : 0;
  a1=arg[0]? arg[0][4] : 0;
  a2=(a0*a1);
  a3=arg[0]? arg[0][2] : 0;
  a4=arg[0]? arg[0][5] : 0;
  a5=(a3*a4);
  a2=(a2+a5);
  a5=arg[0]? arg[0][3] : 0;
  a6=arg[0]? arg[0][6] : 0;
  a7=(a5*a6);
  a2=(a2+a7);
  a7=2.;
  a2=(a2/a7);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0]? arg[0][0] : 0;
  a8=(a2*a1);
  a9=(a3*a6);
  a10=(a5*a4);
  a9=(a9-a10);
  a8=(a8+a9);
  a8=(a8/a7);
  a8=(-a8);
  if (res[0]!=0) res[0][1]=a8;
  a8=(a2*a4);
  a9=(a5*a1);
  a10=(a0*a6);
  a9=(a9-a10);
  a8=(a8+a9);
  a8=(a8/a7);
  a8=(-a8);
  if (res[0]!=0) res[0][2]=a8;
  a8=(a2*a6);
  a9=(a0*a4);
  a10=(a3*a1);
  a9=(a9-a10);
  a8=(a8+a9);
  a8=(a8/a7);
  a8=(-a8);
  if (res[0]!=0) res[0][3]=a8;
  a8=-5.;
  a7=arg[2]? arg[2][24] : 0;
  a7=(a8*a7);
  a9=arg[2]? arg[2][6] : 0;
  a10=arg[0]? arg[0][8] : 0;
  a11=(a9*a10);
  a12=arg[2]? arg[2][5] : 0;
  a13=arg[0]? arg[0][7] : 0;
  a14=(a12*a13);
  a11=(a11-a14);
  a14=arg[2]? arg[2][7] : 0;
  a15=arg[0]? arg[0][9] : 0;
  a16=(a14*a15);
  a11=(a11+a16);
  a16=arg[2]? arg[2][8] : 0;
  a17=arg[0]? arg[0][10] : 0;
  a18=(a16*a17);
  a11=(a11-a18);
  a18=arg[2]? arg[2][4] : 0;
  a19=(a18*a6);
  a20=(a4*a19);
  a21=arg[2]? arg[2][3] : 0;
  a22=(a21*a4);
  a23=(a6*a22);
  a20=(a20-a23);
  a11=(a11-a20);
  a20=arg[2]? arg[2][2] : 0;
  a11=(a11/a20);
  a7=(a7-a11);
  if (res[0]!=0) res[0][4]=a7;
  a7=arg[2]? arg[2][25] : 0;
  a7=(a8*a7);
  a11=arg[2]? arg[2][10] : 0;
  a23=(a11*a10);
  a24=arg[2]? arg[2][9] : 0;
  a25=(a24*a13);
  a23=(a23-a25);
  a25=arg[2]? arg[2][11] : 0;
  a26=(a25*a15);
  a23=(a23-a26);
  a26=arg[2]? arg[2][12] : 0;
  a27=(a26*a17);
  a23=(a23+a27);
  a27=(a20*a1);
  a28=(a6*a27);
  a29=(a1*a19);
  a28=(a28-a29);
  a23=(a23-a28);
  a23=(a23/a21);
  a7=(a7-a23);
  if (res[0]!=0) res[0][5]=a7;
  a7=arg[2]? arg[2][26] : 0;
  a8=(a8*a7);
  a7=arg[2]? arg[2][13] : 0;
  a10=(a7*a10);
  a13=(a7*a13);
  a10=(a10-a13);
  a15=(a7*a15);
  a10=(a10-a15);
  a17=(a7*a17);
  a10=(a10+a17);
  a17=(a1*a22);
  a15=(a4*a27);
  a17=(a17-a15);
  a10=(a10-a17);
  a10=(a10/a18);
  a8=(a8-a10);
  if (res[0]!=0) res[0][6]=a8;
  a8=5.0000000000000000e-01;
  a10=(a8*a1);
  a10=(-a10);
  if (res[1]!=0) res[1][0]=a10;
  a10=(a8*a4);
  a10=(-a10);
  if (res[1]!=0) res[1][1]=a10;
  a10=(a8*a6);
  a10=(-a10);
  if (res[1]!=0) res[1][2]=a10;
  a10=(a8*a1);
  if (res[1]!=0) res[1][3]=a10;
  a10=(a8*a6);
  if (res[1]!=0) res[1][4]=a10;
  a10=(a8*a4);
  a10=(-a10);
  if (res[1]!=0) res[1][5]=a10;
  a10=(a8*a4);
  if (res[1]!=0) res[1][6]=a10;
  a10=(a8*a6);
  a10=(-a10);
  if (res[1]!=0) res[1][7]=a10;
  a10=(a8*a1);
  if (res[1]!=0) res[1][8]=a10;
  a10=(a8*a6);
  if (res[1]!=0) res[1][9]=a10;
  a10=(a8*a4);
  if (res[1]!=0) res[1][10]=a10;
  a10=(a8*a1);
  a10=(-a10);
  if (res[1]!=0) res[1][11]=a10;
  a10=(a8*a0);
  if (res[1]!=0) res[1][12]=a10;
  a10=(a8*a2);
  a10=(-a10);
  if (res[1]!=0) res[1][13]=a10;
  a10=(a8*a5);
  a10=(-a10);
  if (res[1]!=0) res[1][14]=a10;
  a10=(a8*a3);
  if (res[1]!=0) res[1][15]=a10;
  a10=(a6*a20);
  a10=(a10-a19);
  a10=(a10/a21);
  if (res[1]!=0) res[1][16]=a10;
  a10=(a4*a20);
  a10=(a22-a10);
  a10=(a10/a18);
  if (res[1]!=0) res[1][17]=a10;
  a10=(a8*a3);
  if (res[1]!=0) res[1][18]=a10;
  a10=(a8*a5);
  if (res[1]!=0) res[1][19]=a10;
  a10=(a8*a2);
  a10=(-a10);
  if (res[1]!=0) res[1][20]=a10;
  a10=(a8*a0);
  a10=(-a10);
  if (res[1]!=0) res[1][21]=a10;
  a6=(a6*a21);
  a19=(a19-a6);
  a19=(a19/a20);
  if (res[1]!=0) res[1][22]=a19;
  a19=(a1*a21);
  a19=(a19-a27);
  a19=(a19/a18);
  if (res[1]!=0) res[1][23]=a19;
  a5=(a8*a5);
  if (res[1]!=0) res[1][24]=a5;
  a3=(a8*a3);
  a3=(-a3);
  if (res[1]!=0) res[1][25]=a3;
  a0=(a8*a0);
  if (res[1]!=0) res[1][26]=a0;
  a8=(a8*a2);
  a8=(-a8);
  if (res[1]!=0) res[1][27]=a8;
  a4=(a4*a18);
  a4=(a4-a22);
  a4=(a4/a20);
  if (res[1]!=0) res[1][28]=a4;
  a1=(a1*a18);
  a27=(a27-a1);
  a27=(a27/a21);
  if (res[1]!=0) res[1][29]=a27;
  a12=(a12/a20);
  if (res[1]!=0) res[1][30]=a12;
  a24=(a24/a21);
  if (res[1]!=0) res[1][31]=a24;
  a24=(a7/a18);
  if (res[1]!=0) res[1][32]=a24;
  a9=(a9/a20);
  a9=(-a9);
  if (res[1]!=0) res[1][33]=a9;
  a11=(a11/a21);
  a11=(-a11);
  if (res[1]!=0) res[1][34]=a11;
  a11=(a7/a18);
  a11=(-a11);
  if (res[1]!=0) res[1][35]=a11;
  a14=(a14/a20);
  a14=(-a14);
  if (res[1]!=0) res[1][36]=a14;
  a25=(a25/a21);
  if (res[1]!=0) res[1][37]=a25;
  a25=(a7/a18);
  if (res[1]!=0) res[1][38]=a25;
  a16=(a16/a20);
  if (res[1]!=0) res[1][39]=a16;
  a26=(a26/a21);
  a26=(-a26);
  if (res[1]!=0) res[1][40]=a26;
  a7=(a7/a18);
  a7=(-a7);
  if (res[1]!=0) res[1][41]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_fun_jac_y(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_fun_jac_y_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_fun_jac_y_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_phi_fun_jac_y_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_fun_jac_y_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_phi_fun_jac_y_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_phi_fun_jac_y_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_ode_gnsf_phi_fun_jac_y_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_gnsf_phi_fun_jac_y_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_gnsf_phi_fun_jac_y_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real drone_ode_gnsf_phi_fun_jac_y_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_gnsf_phi_fun_jac_y_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_gnsf_phi_fun_jac_y_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_gnsf_phi_fun_jac_y_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_gnsf_phi_fun_jac_y_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_fun_jac_y_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_gnsf_phi_fun_jac_y_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
