/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_ode_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[31] = {27, 1, 0, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26};
static const casadi_int casadi_s4[59] = {13, 13, 0, 0, 0, 0, 5, 11, 17, 22, 23, 24, 25, 31, 37, 43, 4, 5, 6, 7, 8, 3, 5, 6, 7, 8, 9, 3, 4, 6, 7, 8, 9, 3, 4, 5, 7, 8, 0, 1, 2, 3, 4, 5, 6, 11, 12, 3, 4, 5, 6, 10, 12, 3, 4, 5, 6, 10, 11};
static const casadi_int casadi_s5[29] = {13, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s6[31] = {13, 4, 0, 6, 12, 18, 24, 7, 8, 9, 10, 11, 12, 7, 8, 9, 10, 11, 12, 7, 8, 9, 10, 11, 12, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s7[3] = {13, 0, 0};

/* drone_ode_impl_dae_jac_x_xdot_u_z:(i0[13],i1[13],i2[4],i3[],i4[],i5[27])->(o0[13x13,43nz],o1[13x13,13nz],o2[13x4,24nz],o3[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.0000000000000000e-01;
  a1=arg[0]? arg[0][10] : 0;
  a2=(a0*a1);
  a2=(-a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0]? arg[0][11] : 0;
  a3=(a0*a2);
  a3=(-a3);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[0]? arg[0][12] : 0;
  a4=(a0*a3);
  a4=(-a4);
  if (res[0]!=0) res[0][2]=a4;
  a4=arg[2]? arg[2][0] : 0;
  a5=arg[2]? arg[2][1] : 0;
  a4=(a4+a5);
  a5=arg[2]? arg[2][2] : 0;
  a4=(a4+a5);
  a5=arg[2]? arg[2][3] : 0;
  a4=(a4+a5);
  a5=2.;
  a6=arg[0]? arg[0][5] : 0;
  a7=(a5*a6);
  a8=(a4*a7);
  a9=arg[5]? arg[5][0] : 0;
  a8=(a8/a9);
  a8=(-a8);
  if (res[0]!=0) res[0][3]=a8;
  a8=arg[0]? arg[0][4] : 0;
  a10=(a5*a8);
  a11=(a4*a10);
  a11=(a11/a9);
  if (res[0]!=0) res[0][4]=a11;
  a11=(a0*a1);
  if (res[0]!=0) res[0][5]=a11;
  a11=(a0*a3);
  if (res[0]!=0) res[0][6]=a11;
  a11=(a0*a2);
  a11=(-a11);
  if (res[0]!=0) res[0][7]=a11;
  a11=arg[0]? arg[0][6] : 0;
  a12=(a5*a11);
  a12=(a4*a12);
  a12=(a12/a9);
  a12=(-a12);
  if (res[0]!=0) res[0][8]=a12;
  a12=arg[0]? arg[0][3] : 0;
  a13=(a5*a12);
  a13=(a4*a13);
  a13=(a13/a9);
  if (res[0]!=0) res[0][9]=a13;
  a13=(a8+a8);
  a13=(a5*a13);
  a13=(a4*a13);
  a13=(a13/a9);
  if (res[0]!=0) res[0][10]=a13;
  a13=(a0*a2);
  if (res[0]!=0) res[0][11]=a13;
  a13=(a0*a3);
  a13=(-a13);
  if (res[0]!=0) res[0][12]=a13;
  a13=(a0*a1);
  if (res[0]!=0) res[0][13]=a13;
  a13=(a5*a12);
  a13=(a4*a13);
  a13=(a13/a9);
  a13=(-a13);
  if (res[0]!=0) res[0][14]=a13;
  a13=(a5*a11);
  a13=(a4*a13);
  a13=(a13/a9);
  a13=(-a13);
  if (res[0]!=0) res[0][15]=a13;
  a13=(a6+a6);
  a13=(a5*a13);
  a13=(a4*a13);
  a13=(a13/a9);
  if (res[0]!=0) res[0][16]=a13;
  a13=(a0*a3);
  if (res[0]!=0) res[0][17]=a13;
  a13=(a0*a2);
  if (res[0]!=0) res[0][18]=a13;
  a13=(a0*a1);
  a13=(-a13);
  if (res[0]!=0) res[0][19]=a13;
  a13=(a5*a8);
  a14=(a4*a13);
  a14=(a14/a9);
  a14=(-a14);
  if (res[0]!=0) res[0][20]=a14;
  a14=(a5*a6);
  a4=(a4*a14);
  a4=(a4/a9);
  a4=(-a4);
  if (res[0]!=0) res[0][21]=a4;
  a4=-1.;
  if (res[0]!=0) res[0][22]=a4;
  if (res[0]!=0) res[0][23]=a4;
  if (res[0]!=0) res[0][24]=a4;
  a4=(a0*a8);
  if (res[0]!=0) res[0][25]=a4;
  a4=(a0*a12);
  a4=(-a4);
  if (res[0]!=0) res[0][26]=a4;
  a4=(a0*a11);
  a4=(-a4);
  if (res[0]!=0) res[0][27]=a4;
  a4=(a0*a6);
  if (res[0]!=0) res[0][28]=a4;
  a4=arg[5]? arg[5][2] : 0;
  a15=(a3*a4);
  a16=arg[5]? arg[5][4] : 0;
  a17=(a16*a3);
  a15=(a15-a17);
  a18=arg[5]? arg[5][3] : 0;
  a15=(a15/a18);
  if (res[0]!=0) res[0][29]=a15;
  a15=(a18*a2);
  a19=(a2*a4);
  a19=(a15-a19);
  a19=(a19/a16);
  if (res[0]!=0) res[0][30]=a19;
  a19=(a0*a6);
  if (res[0]!=0) res[0][31]=a19;
  a19=(a0*a11);
  if (res[0]!=0) res[0][32]=a19;
  a19=(a0*a12);
  a19=(-a19);
  if (res[0]!=0) res[0][33]=a19;
  a19=(a0*a8);
  a19=(-a19);
  if (res[0]!=0) res[0][34]=a19;
  a3=(a3*a18);
  a17=(a17-a3);
  a17=(a17/a4);
  if (res[0]!=0) res[0][35]=a17;
  a17=(a1*a18);
  a3=(a4*a1);
  a17=(a17-a3);
  a17=(a17/a16);
  if (res[0]!=0) res[0][36]=a17;
  a17=(a0*a11);
  if (res[0]!=0) res[0][37]=a17;
  a17=(a0*a6);
  a17=(-a17);
  if (res[0]!=0) res[0][38]=a17;
  a17=(a0*a8);
  if (res[0]!=0) res[0][39]=a17;
  a0=(a0*a12);
  a0=(-a0);
  if (res[0]!=0) res[0][40]=a0;
  a2=(a2*a16);
  a2=(a2-a15);
  a2=(a2/a4);
  if (res[0]!=0) res[0][41]=a2;
  a1=(a1*a16);
  a3=(a3-a1);
  a3=(a3/a18);
  if (res[0]!=0) res[0][42]=a3;
  a3=1.;
  if (res[1]!=0) res[1][0]=a3;
  if (res[1]!=0) res[1][1]=a3;
  if (res[1]!=0) res[1][2]=a3;
  if (res[1]!=0) res[1][3]=a3;
  if (res[1]!=0) res[1][4]=a3;
  if (res[1]!=0) res[1][5]=a3;
  if (res[1]!=0) res[1][6]=a3;
  if (res[1]!=0) res[1][7]=a3;
  if (res[1]!=0) res[1][8]=a3;
  if (res[1]!=0) res[1][9]=a3;
  if (res[1]!=0) res[1][10]=a3;
  if (res[1]!=0) res[1][11]=a3;
  if (res[1]!=0) res[1][12]=a3;
  a13=(a13*a11);
  a7=(a7*a12);
  a13=(a13+a7);
  a7=(a13/a9);
  a7=(-a7);
  if (res[2]!=0) res[2][0]=a7;
  a14=(a14*a11);
  a10=(a10*a12);
  a14=(a14-a10);
  a10=(a14/a9);
  a10=(-a10);
  if (res[2]!=0) res[2][1]=a10;
  a8=casadi_sq(a8);
  a8=(a5*a8);
  a3=(a3-a8);
  a6=casadi_sq(a6);
  a5=(a5*a6);
  a3=(a3-a5);
  a5=(a3/a9);
  a5=(-a5);
  if (res[2]!=0) res[2][2]=a5;
  a5=arg[5]? arg[5][5] : 0;
  a5=(a5/a4);
  if (res[2]!=0) res[2][3]=a5;
  a5=arg[5]? arg[5][9] : 0;
  a5=(a5/a18);
  a5=(-a5);
  if (res[2]!=0) res[2][4]=a5;
  a5=arg[5]? arg[5][13] : 0;
  a6=(a5/a16);
  if (res[2]!=0) res[2][5]=a6;
  a6=(a13/a9);
  a6=(-a6);
  if (res[2]!=0) res[2][6]=a6;
  a6=(a14/a9);
  a6=(-a6);
  if (res[2]!=0) res[2][7]=a6;
  a6=(a3/a9);
  a6=(-a6);
  if (res[2]!=0) res[2][8]=a6;
  a6=arg[5]? arg[5][6] : 0;
  a6=(a6/a4);
  if (res[2]!=0) res[2][9]=a6;
  a6=arg[5]? arg[5][10] : 0;
  a8=(a6/a18);
  if (res[2]!=0) res[2][10]=a8;
  a8=(a5/a16);
  a8=(-a8);
  if (res[2]!=0) res[2][11]=a8;
  a8=(a13/a9);
  a8=(-a8);
  if (res[2]!=0) res[2][12]=a8;
  a8=(a14/a9);
  a8=(-a8);
  if (res[2]!=0) res[2][13]=a8;
  a8=(a3/a9);
  a8=(-a8);
  if (res[2]!=0) res[2][14]=a8;
  a8=arg[5]? arg[5][7] : 0;
  a8=(a8/a4);
  a8=(-a8);
  if (res[2]!=0) res[2][15]=a8;
  a6=(a6/a18);
  if (res[2]!=0) res[2][16]=a6;
  a6=(a5/a16);
  if (res[2]!=0) res[2][17]=a6;
  a13=(a13/a9);
  a13=(-a13);
  if (res[2]!=0) res[2][18]=a13;
  a14=(a14/a9);
  a14=(-a14);
  if (res[2]!=0) res[2][19]=a14;
  a3=(a3/a9);
  a3=(-a3);
  if (res[2]!=0) res[2][20]=a3;
  a3=arg[5]? arg[5][8] : 0;
  a3=(a3/a4);
  a3=(-a3);
  if (res[2]!=0) res[2][21]=a3;
  a3=arg[5]? arg[5][12] : 0;
  a3=(a3/a18);
  a3=(-a3);
  if (res[2]!=0) res[2][22]=a3;
  a5=(a5/a16);
  a5=(-a5);
  if (res[2]!=0) res[2][23]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_ode_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_ode_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_ode_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_ode_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real drone_ode_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_ode_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
