/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[33] = {11, 11, 0, 4, 8, 12, 16, 17, 18, 19, 19, 19, 19, 19, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s5[14] = {0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* drone_ode_cost_ext_cost_e_fun_jac_hess:(i0[11],i1[],i2[],i3[21])->(o0,o1[11],o2[11x11,19nz],o3[],o4[0x11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92;
  a0=2.;
  a1=arg[3]? arg[3][14] : 0;
  a2=casadi_sq(a1);
  a3=arg[3]? arg[3][15] : 0;
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a4=arg[3]? arg[3][16] : 0;
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a5=arg[3]? arg[3][17] : 0;
  a6=casadi_sq(a5);
  a2=(a2+a6);
  a2=sqrt(a2);
  a6=(a1/a2);
  a7=arg[0]? arg[0][1] : 0;
  a8=arg[0]? arg[0][0] : 0;
  a9=casadi_sq(a8);
  a10=casadi_sq(a7);
  a9=(a9+a10);
  a10=arg[0]? arg[0][2] : 0;
  a11=casadi_sq(a10);
  a9=(a9+a11);
  a11=arg[0]? arg[0][3] : 0;
  a12=casadi_sq(a11);
  a9=(a9+a12);
  a9=sqrt(a9);
  a12=(a7/a9);
  a13=(a6*a12);
  a14=(a3/a2);
  a15=(a8/a9);
  a16=(a14*a15);
  a13=(a13-a16);
  a16=(a5/a2);
  a17=(a10/a9);
  a18=(a16*a17);
  a13=(a13-a18);
  a2=(a4/a2);
  a18=(a11/a9);
  a19=(a2*a18);
  a13=(a13-a19);
  a13=(a0*a13);
  a19=casadi_sq(a1);
  a20=casadi_sq(a3);
  a19=(a19+a20);
  a20=casadi_sq(a4);
  a19=(a19+a20);
  a20=casadi_sq(a5);
  a19=(a19+a20);
  a19=sqrt(a19);
  a1=(a1/a19);
  a20=casadi_sq(a8);
  a21=casadi_sq(a7);
  a20=(a20+a21);
  a21=casadi_sq(a10);
  a20=(a20+a21);
  a21=casadi_sq(a11);
  a20=(a20+a21);
  a20=sqrt(a20);
  a21=(a7/a20);
  a22=(a1*a21);
  a3=(a3/a19);
  a23=(a8/a20);
  a24=(a3*a23);
  a22=(a22-a24);
  a5=(a5/a19);
  a24=(a10/a20);
  a25=(a5*a24);
  a22=(a22-a25);
  a4=(a4/a19);
  a19=(a11/a20);
  a25=(a4*a19);
  a22=(a22-a25);
  a25=(a13*a22);
  a26=(a6*a17);
  a27=(a2*a15);
  a28=(a16*a12);
  a27=(a27+a28);
  a26=(a26-a27);
  a27=(a14*a18);
  a26=(a26+a27);
  a26=(a0*a26);
  a27=(a1*a24);
  a28=(a4*a23);
  a29=(a5*a21);
  a28=(a28+a29);
  a27=(a27-a28);
  a28=(a3*a19);
  a27=(a27+a28);
  a28=(a26*a27);
  a25=(a25+a28);
  a28=8.;
  a29=(a2*a12);
  a30=(a16*a15);
  a29=(a29-a30);
  a30=(a14*a17);
  a29=(a29-a30);
  a30=(a6*a18);
  a29=(a29+a30);
  a29=(a28*a29);
  a30=(a4*a21);
  a31=(a5*a23);
  a30=(a30-a31);
  a31=(a3*a24);
  a30=(a30-a31);
  a31=(a1*a19);
  a30=(a30+a31);
  a31=(a29*a30);
  a25=(a25+a31);
  a31=arg[3]? arg[3][18] : 0;
  a32=arg[0]? arg[0][4] : 0;
  a31=(a31-a32);
  a32=casadi_sq(a31);
  a25=(a25+a32);
  a32=arg[3]? arg[3][19] : 0;
  a33=arg[0]? arg[0][5] : 0;
  a32=(a32-a33);
  a33=casadi_sq(a32);
  a25=(a25+a33);
  a33=arg[3]? arg[3][20] : 0;
  a34=arg[0]? arg[0][6] : 0;
  a33=(a33-a34);
  a34=casadi_sq(a33);
  a25=(a25+a34);
  if (res[0]!=0) res[0][0]=a25;
  a25=(a8+a8);
  a34=(a23/a20);
  a35=(a5*a29);
  a36=(a4*a26);
  a35=(a35+a36);
  a36=(a3*a13);
  a35=(a35+a36);
  a36=(a34*a35);
  a37=(a19/a20);
  a38=(a1*a29);
  a39=(a3*a26);
  a38=(a38+a39);
  a39=(a4*a13);
  a38=(a38-a39);
  a39=(a37*a38);
  a40=(a24/a20);
  a41=(a1*a26);
  a42=(a3*a29);
  a41=(a41-a42);
  a42=(a5*a13);
  a41=(a41-a42);
  a42=(a40*a41);
  a39=(a39+a42);
  a36=(a36-a39);
  a39=(a21/a20);
  a29=(a4*a29);
  a26=(a5*a26);
  a29=(a29-a26);
  a13=(a1*a13);
  a29=(a29+a13);
  a13=(a39*a29);
  a36=(a36-a13);
  a13=(a20+a20);
  a36=(a36/a13);
  a26=(a25*a36);
  a42=(a35/a20);
  a26=(a26-a42);
  a30=(a28*a30);
  a43=(a16*a30);
  a27=(a0*a27);
  a44=(a2*a27);
  a43=(a43+a44);
  a22=(a0*a22);
  a44=(a14*a22);
  a43=(a43+a44);
  a44=(a43/a9);
  a26=(a26-a44);
  a45=(a8+a8);
  a46=(a15/a9);
  a47=(a46*a43);
  a48=(a18/a9);
  a49=(a6*a30);
  a50=(a14*a27);
  a49=(a49+a50);
  a50=(a2*a22);
  a49=(a49-a50);
  a50=(a48*a49);
  a51=(a17/a9);
  a52=(a6*a27);
  a53=(a14*a30);
  a52=(a52-a53);
  a53=(a16*a22);
  a52=(a52-a53);
  a53=(a51*a52);
  a50=(a50+a53);
  a47=(a47-a50);
  a50=(a12/a9);
  a30=(a2*a30);
  a27=(a16*a27);
  a30=(a30-a27);
  a22=(a6*a22);
  a30=(a30+a22);
  a22=(a50*a30);
  a47=(a47-a22);
  a22=(a9+a9);
  a47=(a47/a22);
  a27=(a45*a47);
  a26=(a26+a27);
  if (res[1]!=0) res[1][0]=a26;
  a26=(a29/a20);
  a27=(a7+a7);
  a53=(a27*a36);
  a53=(a26+a53);
  a54=(a30/a9);
  a53=(a53+a54);
  a55=(a7+a7);
  a56=(a55*a47);
  a53=(a53+a56);
  if (res[1]!=0) res[1][1]=a53;
  a53=(a41/a20);
  a56=(a10+a10);
  a57=(a56*a36);
  a57=(a53+a57);
  a58=(a52/a9);
  a57=(a57+a58);
  a59=(a10+a10);
  a60=(a59*a47);
  a57=(a57+a60);
  if (res[1]!=0) res[1][2]=a57;
  a57=(a38/a20);
  a60=(a11+a11);
  a61=(a60*a36);
  a61=(a57+a61);
  a62=(a49/a9);
  a61=(a61+a62);
  a63=(a11+a11);
  a64=(a63*a47);
  a61=(a61+a64);
  if (res[1]!=0) res[1][3]=a61;
  a31=(a31+a31);
  a31=(-a31);
  if (res[1]!=0) res[1][4]=a31;
  a32=(a32+a32);
  a32=(-a32);
  if (res[1]!=0) res[1][5]=a32;
  a33=(a33+a33);
  a33=(-a33);
  if (res[1]!=0) res[1][6]=a33;
  a33=0.;
  if (res[1]!=0) res[1][7]=a33;
  if (res[1]!=0) res[1][8]=a33;
  if (res[1]!=0) res[1][9]=a33;
  if (res[1]!=0) res[1][10]=a33;
  a33=(a0*a36);
  a32=(1./a20);
  a23=(a23/a20);
  a31=(a8/a20);
  a61=(a23*a31);
  a32=(a32-a61);
  a61=(a32/a20);
  a64=(a34/a20);
  a65=(a64*a31);
  a61=(a61-a65);
  a61=(a35*a61);
  a17=(a17/a9);
  a8=(a8/a9);
  a65=(a17*a8);
  a66=(a14*a65);
  a12=(a12/a9);
  a67=(a12*a8);
  a68=(a2*a67);
  a69=(1./a9);
  a15=(a15/a9);
  a70=(a15*a8);
  a69=(a69-a70);
  a70=(a16*a69);
  a68=(a68+a70);
  a66=(a66-a68);
  a18=(a18/a9);
  a68=(a18*a8);
  a70=(a6*a68);
  a66=(a66-a70);
  a66=(a28*a66);
  a70=(a5*a66);
  a71=(a6*a65);
  a72=(a2*a69);
  a73=(a16*a67);
  a72=(a72-a73);
  a71=(a71+a72);
  a72=(a14*a68);
  a71=(a71+a72);
  a71=(a0*a71);
  a72=(a4*a71);
  a70=(a70-a72);
  a72=(a16*a65);
  a73=(a6*a67);
  a74=(a14*a69);
  a73=(a73+a74);
  a72=(a72-a73);
  a73=(a2*a68);
  a72=(a72+a73);
  a72=(a0*a72);
  a73=(a3*a72);
  a70=(a70+a73);
  a73=(a34*a70);
  a61=(a61+a73);
  a73=(a1*a66);
  a74=(a3*a71);
  a73=(a73-a74);
  a74=(a4*a72);
  a73=(a73-a74);
  a73=(a37*a73);
  a19=(a19/a20);
  a74=(a19*a31);
  a75=(a74/a20);
  a76=(a37/a20);
  a77=(a76*a31);
  a75=(a75+a77);
  a75=(a38*a75);
  a73=(a73-a75);
  a24=(a24/a20);
  a75=(a24*a31);
  a77=(a75/a20);
  a78=(a40/a20);
  a79=(a78*a31);
  a77=(a77+a79);
  a77=(a41*a77);
  a79=(a1*a71);
  a80=(a3*a66);
  a79=(a79+a80);
  a80=(a5*a72);
  a79=(a79+a80);
  a79=(a40*a79);
  a77=(a77+a79);
  a73=(a73-a77);
  a61=(a61-a73);
  a66=(a4*a66);
  a71=(a5*a71);
  a66=(a66+a71);
  a72=(a1*a72);
  a66=(a66+a72);
  a66=(a39*a66);
  a21=(a21/a20);
  a72=(a21*a31);
  a71=(a72/a20);
  a73=(a39/a20);
  a77=(a73*a31);
  a71=(a71+a77);
  a71=(a29*a71);
  a66=(a66-a71);
  a61=(a61-a66);
  a61=(a61/a13);
  a66=(a36/a13);
  a71=(a31+a31);
  a71=(a66*a71);
  a61=(a61-a71);
  a61=(a25*a61);
  a33=(a33+a61);
  a70=(a70/a20);
  a42=(a42/a20);
  a31=(a42*a31);
  a70=(a70-a31);
  a33=(a33-a70);
  a70=(a3*a75);
  a31=(a4*a72);
  a61=(a5*a32);
  a31=(a31+a61);
  a70=(a70-a31);
  a31=(a1*a74);
  a70=(a70-a31);
  a70=(a28*a70);
  a31=(a16*a70);
  a61=(a1*a75);
  a71=(a4*a32);
  a77=(a5*a72);
  a71=(a71-a77);
  a61=(a61+a71);
  a71=(a3*a74);
  a61=(a61+a71);
  a61=(a0*a61);
  a71=(a2*a61);
  a31=(a31-a71);
  a75=(a5*a75);
  a72=(a1*a72);
  a32=(a3*a32);
  a72=(a72+a32);
  a75=(a75-a72);
  a74=(a4*a74);
  a75=(a75+a74);
  a75=(a0*a75);
  a74=(a14*a75);
  a31=(a31+a74);
  a74=(a31/a9);
  a44=(a44/a9);
  a72=(a44*a8);
  a74=(a74-a72);
  a33=(a33-a74);
  a74=(a0*a47);
  a69=(a69/a9);
  a72=(a46/a9);
  a32=(a72*a8);
  a69=(a69-a32);
  a69=(a43*a69);
  a31=(a46*a31);
  a69=(a69+a31);
  a31=(a6*a70);
  a32=(a14*a61);
  a31=(a31-a32);
  a32=(a2*a75);
  a31=(a31-a32);
  a31=(a48*a31);
  a68=(a68/a9);
  a32=(a48/a9);
  a71=(a32*a8);
  a68=(a68+a71);
  a68=(a49*a68);
  a31=(a31-a68);
  a65=(a65/a9);
  a68=(a51/a9);
  a71=(a68*a8);
  a65=(a65+a71);
  a65=(a52*a65);
  a71=(a6*a61);
  a77=(a14*a70);
  a71=(a71+a77);
  a77=(a16*a75);
  a71=(a71+a77);
  a71=(a51*a71);
  a65=(a65+a71);
  a31=(a31-a65);
  a69=(a69-a31);
  a70=(a2*a70);
  a61=(a16*a61);
  a70=(a70+a61);
  a75=(a6*a75);
  a70=(a70+a75);
  a70=(a50*a70);
  a67=(a67/a9);
  a75=(a50/a9);
  a61=(a75*a8);
  a67=(a67+a61);
  a67=(a30*a67);
  a70=(a70-a67);
  a69=(a69-a70);
  a69=(a69/a22);
  a70=(a47/a22);
  a8=(a8+a8);
  a8=(a70*a8);
  a69=(a69-a8);
  a69=(a45*a69);
  a74=(a74+a69);
  a33=(a33+a74);
  if (res[2]!=0) res[2][0]=a33;
  a33=(1./a9);
  a74=(a7/a9);
  a69=(a12*a74);
  a33=(a33-a69);
  a69=(a2*a33);
  a8=(a15*a74);
  a67=(a16*a8);
  a69=(a69+a67);
  a67=(a17*a74);
  a61=(a14*a67);
  a69=(a69+a61);
  a61=(a18*a74);
  a31=(a6*a61);
  a69=(a69-a31);
  a69=(a28*a69);
  a31=(a5*a69);
  a65=(a6*a67);
  a71=(a16*a33);
  a77=(a2*a8);
  a71=(a71-a77);
  a65=(a65+a71);
  a71=(a14*a61);
  a65=(a65+a71);
  a65=(a0*a65);
  a71=(a4*a65);
  a31=(a31-a71);
  a71=(a6*a33);
  a77=(a14*a8);
  a71=(a71+a77);
  a77=(a16*a67);
  a71=(a71+a77);
  a77=(a2*a61);
  a71=(a71+a77);
  a71=(a0*a71);
  a77=(a3*a71);
  a31=(a31+a77);
  a77=(a34*a31);
  a7=(a7/a20);
  a79=(a23*a7);
  a80=(a79/a20);
  a81=(a64*a7);
  a80=(a80+a81);
  a80=(a35*a80);
  a77=(a77-a80);
  a80=(a1*a69);
  a81=(a3*a65);
  a80=(a80-a81);
  a81=(a4*a71);
  a80=(a80-a81);
  a80=(a37*a80);
  a81=(a19*a7);
  a82=(a81/a20);
  a83=(a76*a7);
  a82=(a82+a83);
  a82=(a38*a82);
  a80=(a80-a82);
  a82=(a24*a7);
  a83=(a82/a20);
  a84=(a78*a7);
  a83=(a83+a84);
  a83=(a41*a83);
  a84=(a1*a65);
  a85=(a3*a69);
  a84=(a84+a85);
  a85=(a5*a71);
  a84=(a84+a85);
  a84=(a40*a84);
  a83=(a83+a84);
  a80=(a80-a83);
  a77=(a77-a80);
  a80=(1./a20);
  a83=(a21*a7);
  a80=(a80-a83);
  a83=(a80/a20);
  a84=(a73*a7);
  a83=(a83-a84);
  a83=(a29*a83);
  a69=(a4*a69);
  a65=(a5*a65);
  a69=(a69+a65);
  a71=(a1*a71);
  a69=(a69+a71);
  a71=(a39*a69);
  a83=(a83+a71);
  a77=(a77-a83);
  a77=(a77/a13);
  a83=(a7+a7);
  a83=(a66*a83);
  a77=(a77-a83);
  a83=(a25*a77);
  a31=(a31/a20);
  a71=(a42*a7);
  a31=(a31-a71);
  a83=(a83-a31);
  a31=(a4*a80);
  a71=(a5*a79);
  a31=(a31+a71);
  a71=(a3*a82);
  a31=(a31+a71);
  a71=(a1*a81);
  a31=(a31-a71);
  a31=(a28*a31);
  a71=(a16*a31);
  a65=(a1*a82);
  a84=(a5*a80);
  a85=(a4*a79);
  a84=(a84-a85);
  a65=(a65+a84);
  a84=(a3*a81);
  a65=(a65+a84);
  a65=(a0*a65);
  a84=(a2*a65);
  a71=(a71-a84);
  a80=(a1*a80);
  a79=(a3*a79);
  a80=(a80+a79);
  a82=(a5*a82);
  a80=(a80+a82);
  a81=(a4*a81);
  a80=(a80+a81);
  a80=(a0*a80);
  a81=(a14*a80);
  a71=(a71+a81);
  a81=(a71/a9);
  a82=(a44*a74);
  a81=(a81-a82);
  a83=(a83-a81);
  a71=(a46*a71);
  a8=(a8/a9);
  a81=(a72*a74);
  a8=(a8+a81);
  a8=(a43*a8);
  a71=(a71-a8);
  a8=(a6*a31);
  a81=(a14*a65);
  a8=(a8-a81);
  a81=(a2*a80);
  a8=(a8-a81);
  a8=(a48*a8);
  a61=(a61/a9);
  a81=(a32*a74);
  a61=(a61+a81);
  a61=(a49*a61);
  a8=(a8-a61);
  a67=(a67/a9);
  a61=(a68*a74);
  a67=(a67+a61);
  a67=(a52*a67);
  a61=(a6*a65);
  a81=(a14*a31);
  a61=(a61+a81);
  a81=(a16*a80);
  a61=(a61+a81);
  a61=(a51*a61);
  a67=(a67+a61);
  a8=(a8-a67);
  a71=(a71-a8);
  a33=(a33/a9);
  a8=(a75*a74);
  a33=(a33-a8);
  a33=(a30*a33);
  a31=(a2*a31);
  a65=(a16*a65);
  a31=(a31+a65);
  a80=(a6*a80);
  a31=(a31+a80);
  a80=(a50*a31);
  a33=(a33+a80);
  a71=(a71-a33);
  a71=(a71/a22);
  a33=(a74+a74);
  a33=(a70*a33);
  a71=(a71-a33);
  a33=(a45*a71);
  a83=(a83+a33);
  if (res[2]!=0) res[2][1]=a83;
  a33=(a10/a9);
  a80=(a15*a33);
  a65=(a16*a80);
  a8=(a12*a33);
  a67=(a2*a8);
  a65=(a65-a67);
  a67=(1./a9);
  a61=(a17*a33);
  a67=(a67-a61);
  a61=(a14*a67);
  a65=(a65-a61);
  a61=(a18*a33);
  a81=(a6*a61);
  a65=(a65-a81);
  a65=(a28*a65);
  a81=(a5*a65);
  a82=(a6*a67);
  a79=(a2*a80);
  a84=(a16*a8);
  a79=(a79+a84);
  a82=(a82+a79);
  a79=(a14*a61);
  a82=(a82-a79);
  a82=(a0*a82);
  a79=(a4*a82);
  a81=(a81+a79);
  a79=(a14*a80);
  a84=(a6*a8);
  a79=(a79-a84);
  a84=(a16*a67);
  a79=(a79-a84);
  a84=(a2*a61);
  a79=(a79+a84);
  a79=(a0*a79);
  a84=(a3*a79);
  a81=(a81+a84);
  a84=(a34*a81);
  a10=(a10/a20);
  a85=(a23*a10);
  a86=(a85/a20);
  a87=(a64*a10);
  a86=(a86+a87);
  a86=(a35*a86);
  a84=(a84-a86);
  a86=(a1*a65);
  a87=(a3*a82);
  a86=(a86+a87);
  a87=(a4*a79);
  a86=(a86-a87);
  a86=(a37*a86);
  a87=(a19*a10);
  a88=(a87/a20);
  a89=(a76*a10);
  a88=(a88+a89);
  a88=(a38*a88);
  a86=(a86-a88);
  a88=(1./a20);
  a89=(a24*a10);
  a88=(a88-a89);
  a89=(a88/a20);
  a90=(a78*a10);
  a89=(a89-a90);
  a89=(a41*a89);
  a90=(a1*a82);
  a91=(a3*a65);
  a90=(a90-a91);
  a91=(a5*a79);
  a90=(a90-a91);
  a91=(a40*a90);
  a89=(a89+a91);
  a86=(a86+a89);
  a84=(a84-a86);
  a65=(a4*a65);
  a82=(a5*a82);
  a65=(a65-a82);
  a79=(a1*a79);
  a65=(a65+a79);
  a79=(a39*a65);
  a82=(a21*a10);
  a86=(a82/a20);
  a89=(a73*a10);
  a86=(a86+a89);
  a86=(a29*a86);
  a79=(a79-a86);
  a84=(a84-a79);
  a84=(a84/a13);
  a79=(a10+a10);
  a79=(a66*a79);
  a84=(a84-a79);
  a79=(a25*a84);
  a81=(a81/a20);
  a86=(a42*a10);
  a81=(a81-a86);
  a79=(a79-a81);
  a81=(a5*a85);
  a86=(a4*a82);
  a81=(a81-a86);
  a86=(a3*a88);
  a81=(a81-a86);
  a86=(a1*a87);
  a81=(a81-a86);
  a81=(a28*a81);
  a86=(a16*a81);
  a89=(a1*a88);
  a91=(a4*a85);
  a92=(a5*a82);
  a91=(a91+a92);
  a89=(a89+a91);
  a91=(a3*a87);
  a89=(a89-a91);
  a89=(a0*a89);
  a91=(a2*a89);
  a86=(a86+a91);
  a85=(a3*a85);
  a82=(a1*a82);
  a85=(a85-a82);
  a88=(a5*a88);
  a85=(a85-a88);
  a87=(a4*a87);
  a85=(a85+a87);
  a85=(a0*a85);
  a87=(a14*a85);
  a86=(a86+a87);
  a87=(a86/a9);
  a88=(a44*a33);
  a87=(a87-a88);
  a79=(a79-a87);
  a86=(a46*a86);
  a80=(a80/a9);
  a87=(a72*a33);
  a80=(a80+a87);
  a80=(a43*a80);
  a86=(a86-a80);
  a80=(a6*a81);
  a87=(a14*a89);
  a80=(a80+a87);
  a87=(a2*a85);
  a80=(a80-a87);
  a80=(a48*a80);
  a61=(a61/a9);
  a87=(a32*a33);
  a61=(a61+a87);
  a61=(a49*a61);
  a80=(a80-a61);
  a67=(a67/a9);
  a61=(a68*a33);
  a67=(a67-a61);
  a67=(a52*a67);
  a61=(a6*a89);
  a87=(a14*a81);
  a61=(a61-a87);
  a87=(a16*a85);
  a61=(a61-a87);
  a87=(a51*a61);
  a67=(a67+a87);
  a80=(a80+a67);
  a86=(a86-a80);
  a81=(a2*a81);
  a89=(a16*a89);
  a81=(a81-a89);
  a85=(a6*a85);
  a81=(a81+a85);
  a85=(a50*a81);
  a8=(a8/a9);
  a89=(a75*a33);
  a8=(a8+a89);
  a8=(a30*a8);
  a85=(a85-a8);
  a86=(a86-a85);
  a86=(a86/a22);
  a85=(a33+a33);
  a85=(a70*a85);
  a86=(a86-a85);
  a85=(a45*a86);
  a79=(a79+a85);
  if (res[2]!=0) res[2][2]=a79;
  a85=(a11/a9);
  a15=(a15*a85);
  a8=(a16*a15);
  a12=(a12*a85);
  a89=(a2*a12);
  a8=(a8-a89);
  a17=(a17*a85);
  a89=(a14*a17);
  a8=(a8+a89);
  a89=(1./a9);
  a18=(a18*a85);
  a89=(a89-a18);
  a18=(a6*a89);
  a8=(a8+a18);
  a8=(a28*a8);
  a18=(a5*a8);
  a80=(a2*a15);
  a67=(a16*a12);
  a80=(a80+a67);
  a67=(a6*a17);
  a80=(a80-a67);
  a67=(a14*a89);
  a80=(a80+a67);
  a80=(a0*a80);
  a67=(a4*a80);
  a18=(a18+a67);
  a67=(a14*a15);
  a87=(a6*a12);
  a67=(a67-a87);
  a87=(a16*a17);
  a67=(a67+a87);
  a87=(a2*a89);
  a67=(a67-a87);
  a67=(a0*a67);
  a87=(a3*a67);
  a18=(a18+a87);
  a34=(a34*a18);
  a11=(a11/a20);
  a23=(a23*a11);
  a87=(a23/a20);
  a64=(a64*a11);
  a87=(a87+a64);
  a35=(a35*a87);
  a34=(a34-a35);
  a35=(1./a20);
  a19=(a19*a11);
  a35=(a35-a19);
  a19=(a35/a20);
  a76=(a76*a11);
  a19=(a19-a76);
  a38=(a38*a19);
  a19=(a1*a8);
  a76=(a3*a80);
  a19=(a19+a76);
  a76=(a4*a67);
  a19=(a19-a76);
  a37=(a37*a19);
  a38=(a38+a37);
  a37=(a1*a80);
  a76=(a3*a8);
  a37=(a37-a76);
  a76=(a5*a67);
  a37=(a37-a76);
  a40=(a40*a37);
  a24=(a24*a11);
  a76=(a24/a20);
  a78=(a78*a11);
  a76=(a76+a78);
  a41=(a41*a76);
  a40=(a40-a41);
  a38=(a38+a40);
  a34=(a34-a38);
  a8=(a4*a8);
  a80=(a5*a80);
  a8=(a8-a80);
  a67=(a1*a67);
  a8=(a8+a67);
  a39=(a39*a8);
  a21=(a21*a11);
  a67=(a21/a20);
  a73=(a73*a11);
  a67=(a67+a73);
  a29=(a29*a67);
  a39=(a39-a29);
  a34=(a34-a39);
  a34=(a34/a13);
  a13=(a11+a11);
  a66=(a66*a13);
  a34=(a34-a66);
  a25=(a25*a34);
  a18=(a18/a20);
  a42=(a42*a11);
  a18=(a18-a42);
  a25=(a25-a18);
  a18=(a5*a23);
  a42=(a4*a21);
  a18=(a18-a42);
  a42=(a3*a24);
  a18=(a18+a42);
  a42=(a1*a35);
  a18=(a18+a42);
  a28=(a28*a18);
  a18=(a16*a28);
  a42=(a4*a23);
  a66=(a5*a21);
  a42=(a42+a66);
  a66=(a1*a24);
  a42=(a42-a66);
  a66=(a3*a35);
  a42=(a42+a66);
  a42=(a0*a42);
  a66=(a2*a42);
  a18=(a18+a66);
  a3=(a3*a23);
  a1=(a1*a21);
  a3=(a3-a1);
  a5=(a5*a24);
  a3=(a3+a5);
  a4=(a4*a35);
  a3=(a3-a4);
  a3=(a0*a3);
  a4=(a14*a3);
  a18=(a18+a4);
  a4=(a18/a9);
  a44=(a44*a85);
  a4=(a4-a44);
  a25=(a25-a4);
  a46=(a46*a18);
  a15=(a15/a9);
  a72=(a72*a85);
  a15=(a15+a72);
  a43=(a43*a15);
  a46=(a46-a43);
  a89=(a89/a9);
  a32=(a32*a85);
  a89=(a89-a32);
  a49=(a49*a89);
  a89=(a6*a28);
  a32=(a14*a42);
  a89=(a89+a32);
  a32=(a2*a3);
  a89=(a89-a32);
  a48=(a48*a89);
  a49=(a49+a48);
  a48=(a6*a42);
  a14=(a14*a28);
  a48=(a48-a14);
  a14=(a16*a3);
  a48=(a48-a14);
  a51=(a51*a48);
  a17=(a17/a9);
  a68=(a68*a85);
  a17=(a17+a68);
  a52=(a52*a17);
  a51=(a51-a52);
  a49=(a49+a51);
  a46=(a46-a49);
  a2=(a2*a28);
  a16=(a16*a42);
  a2=(a2-a16);
  a6=(a6*a3);
  a2=(a2+a6);
  a50=(a50*a2);
  a12=(a12/a9);
  a75=(a75*a85);
  a12=(a12+a75);
  a30=(a30*a12);
  a50=(a50-a30);
  a46=(a46-a50);
  a46=(a46/a22);
  a22=(a85+a85);
  a70=(a70*a22);
  a46=(a46-a70);
  a45=(a45*a46);
  a25=(a25+a45);
  if (res[2]!=0) res[2][3]=a25;
  if (res[2]!=0) res[2][4]=a83;
  a69=(a69/a20);
  a26=(a26/a20);
  a7=(a26*a7);
  a69=(a69-a7);
  a7=(a0*a36);
  a77=(a27*a77);
  a7=(a7+a77);
  a69=(a69+a7);
  a31=(a31/a9);
  a54=(a54/a9);
  a74=(a54*a74);
  a31=(a31-a74);
  a69=(a69+a31);
  a31=(a0*a47);
  a71=(a55*a71);
  a31=(a31+a71);
  a69=(a69+a31);
  if (res[2]!=0) res[2][5]=a69;
  a65=(a65/a20);
  a69=(a26*a10);
  a65=(a65-a69);
  a69=(a27*a84);
  a65=(a65+a69);
  a81=(a81/a9);
  a69=(a54*a33);
  a81=(a81-a69);
  a65=(a65+a81);
  a81=(a55*a86);
  a65=(a65+a81);
  if (res[2]!=0) res[2][6]=a65;
  a8=(a8/a20);
  a26=(a26*a11);
  a8=(a8-a26);
  a27=(a27*a34);
  a8=(a8+a27);
  a2=(a2/a9);
  a54=(a54*a85);
  a2=(a2-a54);
  a8=(a8+a2);
  a55=(a55*a46);
  a8=(a8+a55);
  if (res[2]!=0) res[2][7]=a8;
  if (res[2]!=0) res[2][8]=a79;
  if (res[2]!=0) res[2][9]=a65;
  a90=(a90/a20);
  a53=(a53/a20);
  a10=(a53*a10);
  a90=(a90-a10);
  a10=(a0*a36);
  a84=(a56*a84);
  a10=(a10+a84);
  a90=(a90+a10);
  a61=(a61/a9);
  a58=(a58/a9);
  a33=(a58*a33);
  a61=(a61-a33);
  a90=(a90+a61);
  a61=(a0*a47);
  a86=(a59*a86);
  a61=(a61+a86);
  a90=(a90+a61);
  if (res[2]!=0) res[2][10]=a90;
  a37=(a37/a20);
  a53=(a53*a11);
  a37=(a37-a53);
  a56=(a56*a34);
  a37=(a37+a56);
  a48=(a48/a9);
  a58=(a58*a85);
  a48=(a48-a58);
  a37=(a37+a48);
  a59=(a59*a46);
  a37=(a37+a59);
  if (res[2]!=0) res[2][11]=a37;
  if (res[2]!=0) res[2][12]=a25;
  if (res[2]!=0) res[2][13]=a8;
  if (res[2]!=0) res[2][14]=a37;
  a19=(a19/a20);
  a57=(a57/a20);
  a57=(a57*a11);
  a19=(a19-a57);
  a36=(a0*a36);
  a60=(a60*a34);
  a36=(a36+a60);
  a19=(a19+a36);
  a89=(a89/a9);
  a62=(a62/a9);
  a62=(a62*a85);
  a89=(a89-a62);
  a19=(a19+a89);
  a47=(a0*a47);
  a63=(a63*a46);
  a47=(a47+a63);
  a19=(a19+a47);
  if (res[2]!=0) res[2][15]=a19;
  if (res[2]!=0) res[2][16]=a0;
  if (res[2]!=0) res[2][17]=a0;
  if (res[2]!=0) res[2][18]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real drone_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s4;
    case 3: return casadi_s1;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
