/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_ode_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[31] = {27, 1, 0, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};

/* drone_ode_constr_h_fun:(i0[17],i1[4],i2[],i3[27])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=2.;
  a1=arg[0]? arg[0][5] : 0;
  a2=arg[0]? arg[0][3] : 0;
  a3=(a1+a2);
  a4=casadi_sq(a3);
  a5=arg[0]? arg[0][6] : 0;
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5-a6);
  a8=casadi_sq(a7);
  a4=(a4+a8);
  a4=sqrt(a4);
  a8=(a2-a1);
  a9=casadi_sq(a8);
  a10=(a6+a5);
  a11=casadi_sq(a10);
  a9=(a9+a11);
  a9=sqrt(a9);
  a4=atan2(a4,a9);
  a4=(a0*a4);
  a9=casadi_fabs(a4);
  a11=9.9999999999999995e-08;
  a9=(a9<=a11);
  a12=1.;
  a13=(a9?a12:0);
  a9=(!a9);
  a14=3.1415926535897931e+00;
  a4=(a4-a14);
  a4=casadi_fabs(a4);
  a4=(a4<=a11);
  a4=(a4?a0:0);
  a9=(a9?a4:0);
  a13=(a13+a9);
  a9=0.;
  a4=(a13==a9);
  a10=atan2(a10,a8);
  a7=atan2(a7,a3);
  a3=(a10-a7);
  a3=(a4?a3:0);
  a4=(!a4);
  a13=(a13==a12);
  a10=(a0*a10);
  a10=(a13?a10:0);
  a13=(!a13);
  a7=(a0*a7);
  a7=(-a7);
  a13=(a13?a7:0);
  a10=(a10+a13);
  a4=(a4?a10:0);
  a3=(a3+a4);
  a4=-3.1415926535897931e+00;
  a10=(a3<a4);
  a13=6.2831853071795862e+00;
  a7=(a10?a13:0);
  a10=(!a10);
  a8=(a14<a3);
  a15=-6.2831853071795862e+00;
  a8=(a8?a15:0);
  a10=(a10?a8:0);
  a7=(a7+a10);
  a3=(a3+a7);
  if (res[0]!=0) res[0][0]=a3;
  a3=(a1+a2);
  a3=casadi_sq(a3);
  a7=(a5-a6);
  a7=casadi_sq(a7);
  a3=(a3+a7);
  a3=sqrt(a3);
  a2=(a2-a1);
  a2=casadi_sq(a2);
  a6=(a6+a5);
  a6=casadi_sq(a6);
  a2=(a2+a6);
  a2=sqrt(a2);
  a3=atan2(a3,a2);
  a3=(a0*a3);
  a2=casadi_fabs(a3);
  a2=(a2<=a11);
  a12=(a2?a12:0);
  a2=(!a2);
  a6=(a3-a14);
  a6=casadi_fabs(a6);
  a6=(a6<=a11);
  a6=(a6?a0:0);
  a2=(a2?a6:0);
  a12=(a12+a2);
  a12=(a12==a9);
  a9=(a12?a3:0);
  a12=(!a12);
  a12=(a12?a3:0);
  a9=(a9+a12);
  a12=1.5707963267948966e+00;
  a9=(a9-a12);
  a4=(a9<a4);
  a13=(a4?a13:0);
  a4=(!a4);
  a14=(a14<a9);
  a14=(a14?a15:0);
  a4=(a4?a14:0);
  a13=(a13+a4);
  a9=(a9+a13);
  if (res[0]!=0) res[0][1]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_ode_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_ode_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_ode_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_ode_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_ode_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_ode_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_ode_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_ode_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_ode_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_ode_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_ode_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
